### ISSUE TITLE
Please choose an open source license

### ISSUE THREAD

**Issue by metas-ts** [thedathoudarya/WAGU-data-in-table-view#2]
Hi, 
i guess you are intending to provide this code as open-source and i would like to use your library.
Could you please choose a license for it, such as apache-2.0 or GPL-3.0?

AFAIU, otherwise, a very restrictive "default" license is in effect which forbids people to use your code (let alone redistribute in their own software) without your explicit consent.
I'm not an expert in this matter, i think that's how it is.

Best regards
Tobi

**Comment by fabriciofx** [comment]
+1
