### ISSUE TITLE
Text Formateing is changed while Sharing data: Android

### ISSUE THREAD

**Issue by rajscet** [thedathoudarya/WAGU-data-in-table-view#5]
I want to share diamond detail in table format(Plain text not HTML)

 its prints data properly using the system.out but while I sharing it, its format is changed enter image description here
![untitled](https://user-images.githubusercontent.com/6961313/31268647-f27e7f72-aa9a-11e7-9ed7-42ab4af4ce70.png)

Below is my code

  List<String> headersList = Arrays.asList("", "");
                    List<List<String>> rowsList = Arrays.asList(
                            Arrays.asList("Stone Id :", details[0]),
                            Arrays.asList("Lab", details[1]),
                            Arrays.asList("Shape", details[2]),
                            Arrays.asList("Carat", details[3]),
                            Arrays.asList("Clarity-Color", details[4]),
                            Arrays.asList("Cut-Pol-Sym-Flou", details[5]));

                    Board board = new Board(75);
                    Table table = new Table(board, 75, headersList, rowsList);
                    table.invalidate().setGridMode(Table.GRID_NON).setRowsList(rowsList);
                    List<Integer> colWidthsList = Arrays.asList(30, 14);
                    table.setColWidthsList(colWidthsList);
                    Block tableBlock = table.tableToBlocks();
                    board.setInitialBlock(tableBlock);
                    board.build();
                    String preview1 = board.getPreview();
                    System.out.print(preview1);
                    sharingIntent.putExtra(Intent.EXTRA_TEXT,preview1);

**Comment by thedathoudarya** [comment]
Hi,

To get the table output properly text container should be in [monospace](https://en.wikipedia.org/wiki/Monospaced_font).

Ex:
**Without monospace** - different width for same character count 
123456 - 6 numbers
...... - 6 dots

**With monospace** - same width for same character count
`123456 - 6 numbers`
`...... - 6 dots`
